[build]
target = "x86_64-blog_os.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-blog_os]
runner = "bootimage runner"  # optional if you're using bootimage crate later

[dependencies]
bootloader = "0.9"